language: ruby
os:
  - linux
  - osx
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.2

# Mac OS on Travis doesn't have pre-compiled versions of the 1.9 series
matrix:
  exclude:
    - os: osx
      rvm: 1.9.2
    - os: osx
      rvm: 1.9.3

script: rake test
